server {
    listen 80;
    listen [::]:80;
    server_name dashboard.shensquared.noho.st;

    location / {
        include proxy_params;
        proxy_pass http://unix:/home/shensquared/coursedashboard/dashboard.sock;
    }
 
    access_log /var/log/nginx/dashboard.shensquared.noho.st-access.log;
    error_log /var/log/nginx/dashboard.shensquared.noho.st-error.log;
}

server {
    listen 443 ssl http2;
    # listen [::]:443 ssl http2;
    server_name dashboard.shensquared.noho.st;

    ssl_certificate /etc/yunohost/certs/dashboard.shensquared.noho.st/crt.pem;
    ssl_certificate_key /etc/yunohost/certs/dashboard.shensquared.noho.st/key.pem;

    
    # more_set_headers "Strict-Transport-Security : max-age=63072000; includeSubDomains; preload";
    
    
    # OCSP settings
    ssl_stapling on;
    ssl_stapling_verify on;
    ssl_trusted_certificate /etc/yunohost/certs/dashboard.shensquared.noho.st/crt.pem;

    resolver_timeout 5s;


    include /etc/nginx/conf.d/dashboard.shensquared.noho.st.d/*.conf;


    access_log /var/log/nginx/dashboard.shensquared.noho.st-access.log;
    error_log /var/log/nginx/dashboard.shensquared.noho.st-error.log;
}

# # vhost dedicated to XMPP http_upload
# server {
#     listen 443 ssl http2;
#     listen [::]:443 ssl http2;
#     server_name xmpp-upload.dashboard.shensquared.noho.st;
#     root /dev/null;

#     location /upload/ {
#         alias /var/xmpp-upload/dashboard.shensquared.noho.st/upload/;
#         # Pass all requests to metronome, except for GET and HEAD requests.
#         limit_except GET HEAD {
#           proxy_pass http://localhost:5290;
#         }

#         include proxy_params;
#         add_header 'Access-Control-Allow-Origin' '*';
#         add_header 'Access-Control-Allow-Methods' 'HEAD, GET, PUT, OPTIONS';
#         add_header 'Access-Control-Allow-Headers' 'Authorization';
#         add_header 'Access-Control-Allow-Credentials' 'true';
#         client_max_body_size 105M; # Choose a value a bit higher than the max upload configured in XMPP server
#     }

#     include /etc/nginx/conf.d/security.conf.inc;

#     ssl_certificate /etc/yunohost/certs/dashboard.shensquared.noho.st/crt.pem;
#     ssl_certificate_key /etc/yunohost/certs/dashboard.shensquared.noho.st/key.pem;

    
#     more_set_headers "Strict-Transport-Security : max-age=63072000; includeSubDomains; preload";
    
    
#     # OCSP settings
#     ssl_stapling on;
#     ssl_stapling_verify on;
#     ssl_trusted_certificate /etc/yunohost/certs/dashboard.shensquared.noho.st/crt.pem;
#     resolver 127.0.0.1 127.0.1.1 valid=300s;
#     resolver_timeout 5s;


#     access_log /var/log/nginx/xmpp-upload.dashboard.shensquared.noho.st-access.log;
#     error_log /var/log/nginx/xmpp-upload.dashboard.shensquared.noho.st-error.log;
# }